version: "3"
services:
  api:
    image: ghcr.io/liningtonlab/npmrd_curator_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./npmrd_curator:/app/npmrd_curator
    command: "bash /start-reload.sh"

  app:
    image: ghcr.io/liningtonlab/npmrd_curator_app:latest
    build:
      context: ./npmrd_curator_app
      dockerfile: Dockerfile
    volumes:
    - ./npmrd_curator_app:/app/
    command: "yarn dev"

