version: "3"
services:
  traefik:
    image: traefik:2.1
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --providers.docker
      - --api.dashboard=true
      - --api.insecure=true
      - --accesslog
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
    ports:
      # The HTTP(S) port
      - "80:80"
      # The traefik port
      # - "8889:8080"
    restart: always
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  api:
    image: ghcr.io/liningtonlab/npmrd_curator_api:latest
    restart: always
    # Use this if you want a Sqlite DB
    # volumes:
    #   - ./db:/app/db/
    labels:
      - "traefik.http.routers.npmrd_curator-api.entrypoints=web"
      - "traefik.http.routers.npmrd_curator-api.rule=PathPrefix(`/api`)"
    # Use this if you want a postgres database
    # environment:
    #   - POSTGRES_URI="postgresql://user:password@postgresserver/db"

  app:
    image: ghcr.io/liningtonlab/npmrd_curator_app:latest
    restart: always
    labels:
      - "traefik.http.routers.npmrd_curator.entrypoints=web"
      - "traefik.http.routers.npmrd_curator.rule=PathPrefix(`/`)"

