name: curator 
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - fastapi
  - pydantic
  - uvicorn
  - pandas
  - rdkit
  - sqlalchemy
  - sqlite
  - beautifulsoup4
  - lxml
  - pip:
    - 'nmr_html_parser @ git+https://github.com/liningtonlab/html-parser'
