name: curator 
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - fastapi
  - pydantic
  - uvicorn
  - pandas
  - rdkit
  - sqlalchemy
  - sqlite
  - beautifulsoup4
  - lxml
  - jinja2
