name: api
channels:
  - conda-forge
  - defaults
dependencies:
  - fastapi
  - pydantic
  - uvicorn
  - pandas
  - rdkit
  - sqlalchemy
  - sqlite
  - beautifulsoup4
  - lxml
  - pip:
    - 'nmr_html_parser @ git+ssh://git@https://github.com/liningtonlab/html-parser'